#  Error handling
본격적으로 node.js를 배우기 시작했다. 오늘 배운 것 중에서 가장 인상에 남은 것은  Error handling이다. 

``` 
에러 핸들링(Error handling) 이란?
    
에러 핸들링은 에러를 관리하는 방법이다. 예상치 못한 상황에 대처하는 방식이다. 에러는 예상할 수 있는 에러와 예상치 못한 에러로 구분할 수 있는데, 일반적인 어플리케이션을 설계할 때에는 예상치 못한 에러 상황이 더욱 많이 일어날 것으로 가정해야한다. 
```

에러 핸들링은 우리 사회에서도 쉽게 찾아 볼 수 있다. 예를 들어서 카드로 계산을 할때 통장 안에 들어있는 잔고가 부족하면 강제적으로 에러를 일으켜 계산을 멈추게 한다. 실생활에서도 쉽게 쓰이고 있다.

에러 핸들링에는 세 가지의 방법이 있다.

1. try / catch
```javascript
const users = ["Lee", "Kim", "Park", 2];

try {
  for (const user of users) {
    console.log(user.toUpperCase());
  }
} catch (err) {
  console.error(`Error: ${err.message}`);
}

// LEE
// KIM
// PARK
// Error: user.toUpperCase is not a function
```
try / catch는 서버에서 에러가 일어났을때 예외 처리를 진행한다. 위에서는 소문자를 대문자로 바꾸는 `String.toUpperCase()` 함수에 users가 들어간다. 근데 users에 들어있는 인자중 2는 숫자이다. 대문자로 바꿀 수 없다. 따라서 함수가 돌아갈때 오류가 생긴다. try / catch는 프로그램을 멈추지 않고 에러를 기록한다. 하지만 이렇게 에러를 계속 기록하다가는 상당한 메모리를 잡아먹을 것이다.

2.finally
```javascript
function errorException(isThrow) {
  try {
    console.log('자원을 할당하였습니다.');
    if (isThrow) throw new Error();
  } catch (error) {
    console.log('에러가 발생했습니다.');
  } finally {
    console.log('자원을 제거하였습니다.');
  }
}

errorException(false);
// 자원을 할당하였습니다.
// 자원을 제거하였습니다.
errorException(true);
// 자원을 할당하였습니다.
// 에러가 발생했습니다.
// 자원을 제거하였습니다.
```
`try` 에서는 HTTP연결이 되고 있거나 파일과 같은 특정한 ‘**자원**’을 가지고 처리할 때가 있다. 하지만 해당 ‘**자원**'을 계속 가지고 있으면, 무의미한 메모리를 차지하게 될 것 이므로 에러 여부와 상관없이 일정 시점에서는 해당 ‘**자원**'을 삭제 시킬 필요가 있다. 그때 사용하는 것이 `finally`이다. `finally`는 에러가 발생했는지 여부와 상관없이 언제든지 실행한다.

3.throw
```javascript
function withdraw(amount, account) {
  if (amount > account.balance)
    throw new Error("잔고가 부족합니다.");
  account.balance -= amount;
	console.log(`현재 잔고가 ${account.balance}남았습니다.`); // 출력되지 않음
}

const account = { balance: 1000 };
withdraw(2000, account);

// Error: 잔고가 부족합니다.
```
throw는 처음에 에러 핸들링을 설명할때 예시로 든 사항이다. throw를 호출하면 그 즉시 현재 실행되고 있는 함수는 실행은 멈추게 된다.


이렇듯 에러 핸들링은 생소한 이름과는 다르게 우리 생활의 아주 가까운 곳에서 볼 수 있다. 개인적으로 throw가 아주 재밌어 보였다. 곧 만들 개인 과제에 넣을 수 있다면 throw를 사용해 볼 것이다.


